/* eslint-disable camelcase */
/**
 * Types generated by `yarn generate-types`. Do not edit manually.
 *
 * Version: 0.4.4
 * Api Level: 6
 * Api Compatible: 0
 * Api Prerelease: false
 */

/**
 * UI events types emitted by `redraw` event. Do not edit manually.
 * More info: https://neovim.io/doc/user/ui.html
 */
export type UiEvents = {
  mode_info_set: [enabled: boolean, cursor_styles: Array<any>];

  update_menu: [];

  busy_start: [];

  busy_stop: [];

  mouse_on: [];

  mouse_off: [];

  mode_change: [mode: string, mode_idx: number];

  bell: [];

  visual_bell: [];

  flush: [];

  suspend: [];

  set_title: [title: string];

  set_icon: [icon: string];

  option_set: [name: string, value: any];

  update_fg: [fg: number];

  update_bg: [bg: number];

  update_sp: [sp: number];

  resize: [width: number, height: number];

  clear: [];

  eol_clear: [];

  cursor_goto: [row: number, col: number];

  highlight_set: [attrs: Record<string, any>];

  put: [str: string];

  set_scroll_region: [top: number, bot: number, left: number, right: number];

  scroll: [count: number];

  default_colors_set: [
    rgb_fg: number,
    rgb_bg: number,
    rgb_sp: number,
    cterm_fg: number,
    cterm_bg: number,
  ];

  hl_attr_define: [
    id: number,
    rgb_attrs: Record<string, any>,
    cterm_attrs: Record<string, any>,
    info: Array<any>,
  ];

  hl_group_set: [name: string, id: number];

  grid_resize: [grid: number, width: number, height: number];

  grid_clear: [grid: number];

  grid_cursor_goto: [grid: number, row: number, col: number];

  grid_line: [grid: number, row: number, col_start: number, data: Array<any>];

  grid_scroll: [
    grid: number,
    top: number,
    bot: number,
    left: number,
    right: number,
    rows: number,
    cols: number,
  ];

  grid_destroy: [grid: number];

  win_pos: [
    grid: number,
    win: number,
    startrow: number,
    startcol: number,
    width: number,
    height: number,
  ];

  win_float_pos: [
    grid: number,
    win: number,
    anchor: string,
    anchor_grid: number,
    anchor_row: number,
    anchor_col: number,
    focusable: boolean,
  ];

  win_external_pos: [grid: number, win: number];

  win_hide: [grid: number];

  win_close: [grid: number];

  msg_set_pos: [grid: number, row: number, scrolled: boolean, sep_char: string];

  popupmenu_show: [items: Array<any>, selected: number, row: number, col: number, grid: number];

  popupmenu_hide: [];

  popupmenu_select: [selected: number];

  tabline_update: [current: number, tabs: Array<any>];

  cmdline_show: [
    content: Array<any>,
    pos: number,
    firstc: string,
    prompt: string,
    indent: number,
    level: number,
  ];

  cmdline_pos: [pos: number, level: number];

  cmdline_special_char: [c: string, shift: boolean, level: number];

  cmdline_hide: [level: number];

  cmdline_block_show: [lines: Array<any>];

  cmdline_block_append: [lines: Array<any>];

  cmdline_block_hide: [];

  wildmenu_show: [items: Array<any>];

  wildmenu_select: [selected: number];

  wildmenu_hide: [];

  msg_show: [kind: string, content: Array<any>, replace_last: boolean];

  msg_clear: [];

  msg_showcmd: [content: Array<any>];

  msg_showmode: [content: Array<any>];

  msg_ruler: [content: Array<any>];

  msg_history_show: [entries: Array<any>];
};
