# This workflow will do a clean install of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests and Linter 

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Get Yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache Yarn
      uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-${{ runner.os }}-

    - name: Install Dependencies
      run: yarn

    - name: Build Browser Renderer
      run: yarn build:browser-renderer

    - name: Run ESLint
      run: yarn lint
      if: always()

    - name: Run Tests
      run: yarn test
      if: always()

    - name: Run TypeScript check
      run: yarn typecheck
      if: always()

